// XpressBees B2B Environment Keys
export const XPRESSBEES_B2B_ENV_KEYS = {
  BASE_URL: 'XPRESSBEES_B2B_BASE_URL',
  AUTH_EMAIL: 'XPRESSBEES_B2B_AUTH_EMAIL',
  AUTH_PASSWORD: 'XPRESSBEES_B2B_AUTH_PASSWORD',
  AUTH_PATH: 'XPRESSBEES_B2B_AUTH_PATH',
  CREATE_ORDER_PATH: 'XPRESSBEES_B2B_CREATE_ORDER_PATH',
  CANCEL_ORDER_PATH: 'XPRESSBEES_B2B_CANCEL_ORDER_PATH',
  CREATE_MANIFEST_PATH: 'XPRESSBEES_B2B_CREATE_MANIFEST_PATH',
};

// XpressBees B2B Default Values
export const XPRESSBEES_B2B_DEFAULTS = {
  BASE_URL: 'https://ship.xpressbees.com',
  AUTH_PATH: '/api/users/franchise_login',
  CREATE_ORDER_PATH: '/api/b2b/shipments',
  CANCEL_ORDER_PATH: '/api/b2b/shipments/cancel_shipment',
  CREATE_MANIFEST_PATH: '/api/b2b/manifest',
  PICKUP_LOCATION: 'franchise',
  COURIER_ID: '16949',
};

// XpressBees B2B Constants
export const XPRESSBEES_B2B_CONSTANTS = {
  DEFAULT_TIMEOUT: 30000,
  TOKEN_EXPIRY_BUFFER: 300000, // 5 minutes buffer before token expires
  PICKUP_LOCATION: XPRESSBEES_B2B_DEFAULTS.PICKUP_LOCATION,
  COURIER_ID: XPRESSBEES_B2B_DEFAULTS.COURIER_ID,
};






