export const NETWORK_PARTNER_PROVIDER_CONST = {
    BIGSHIP: 'NETWORK_PARTNER.BIGSHIP',
    TSAW: 'NETWORK_PARTNER.TSAW',
    DEFAULT: 'NETWORK_PARTNER.DEFAULT',
    FACTORY_INIT: 'NETWORK_PARTNER.FACTORY_INIT',
} as const;