export const NETWORK_PARTNER_PROVIDER_CONST = {
    BIGSHIP: 'NETWORK_PARTNER.BIGSHIP',
    TSAW: 'NETWORK_PARTNER.TSAW',
    SHIPYAARI: 'NETWORK_PARTNER.SHIPYAARI',
    DHL: 'NETWORK_PARTNER.DHL',
    INDIA_POST: 'NETWORK_PARTNER.INDIA_POST',
    DEFAULT: 'NETWORK_PARTNER.DEFAULT',
    FACTORY_INIT: 'NETWORK_PARTNER.FACTORY_INIT',
    SMILE_HYPERLOCAL: 'NETWORK_PARTNER.SMILE_HYPERLOCAL',
    PORTER: 'NETWORK_PARTNER.PORTER',
} as const;