export const NETWORK_PARTNER_PROVIDER_CONST = {
    BIGSHIP: 'NETWORK_PARTNER.BIGSHIP',
    TSAW: 'NETWORK_PARTNER.TSAW',
    SHIPYAARI: 'NETWORK_PARTNER.SHIPYAARI',
    DHL: 'NETWORK_PARTNER.DHL',
    UNIUNI: 'NETWORK_PARTNER.UNIUNI',
    DEFAULT: 'NETWORK_PARTNER.DEFAULT',
    FACTORY_INIT: 'NETWORK_PARTNER.FACTORY_INIT',
    SMILE_HYPERLOCAL: 'NETWORK_PARTNER.SMILE_HYPERLOCAL',
    PORTER: 'NETWORK_PARTNER.PORTER',
    SMILE_HUBOPS: "NETWORK_PARTNER.SMILE_HUBOPS",
    ARAMEX: 'NETWORK_PARTNER.ARAMEX',
    FEDEX: 'NETWORK_PARTNER.FEDEX',
    URBANBOLT: 'NETWORK_PARTNER.URBANBOLT',
    BARAL: 'NETWORK_PARTNER.BARAL',
    SHIPCUBE: 'NETWORK_PARTNER.SHIPCUBE',
    XPRESSBEES: 'NETWORK_PARTNER.XPRESSBEES'
} as const;

