export const INDIAPOST_INTERNATIONAL_ENV_KEYS = {
  BASE_URL: 'INDIAPOST_INTERNATIONAL_BASE_URL',
  AUTH_PATH: 'INDIAPOST_INTERNATIONAL_AUTH_PATH',
  CREATE_ORDER_PATH: 'INDIAPOST_INTERNATIONAL_CREATE_ORDER_PATH',
  CREATE_LABEL_PATH: 'INDIAPOST_INTERNATIONAL_CREATE_LABEL_PATH',
  USERNAME: 'INDIAPOST_INTERNATIONAL_USERNAME',
  PASSWORD: 'INDIAPOST_INTERNATIONAL_PASSWORD',
};

export const INDIAPOST_INTERNATIONAL_DEFAULTS = {
  BASE_URL: 'https://test.cept.gov.in',
  AUTH_PATH: '/beextcustomer/v1/access/login',
  CREATE_ORDER_PATH: '/becustomer/v1/crm/international-booking',
  CREATE_LABEL_PATH: '/beextcustomer/v1/label/create',
  USERNAME: '9999999999',
  PASSWORD: 'Dop@1234',
};

export const INDIAPOST_INTERNATIONAL_CONSTANTS = {
  TOKEN_REFRESH_BUFFER_SECONDS: 300, // 5 minutes
  DEFAULT_TIMEOUT: 30000,
};




