export enum AUTH_TYPE {
  SELLER = 'SELLER',
  SHIPPER = 'SHIPPER',
  MANAGEMENT_PORTAL = 'MANAGEMENT_PORTAL',
  CONSUMER = 'CONSUMER',
  GUEST_CONSUMER = 'GUEST_CONSUMER',
  DELIVERY_AGENT = 'DELIVERY_AGENT',
  COD_CENTER = 'COD_CENTER',
  ODD_APP = 'ODD_APP',
}

export const JWT_ENV_CONST = {
  ACCESS_TOKEN_SECRET: 'ACCESS_TOKEN_SECRET',
  ACCESS_TOKEN_EXPIRES_IN: 'ACCESS_TOKEN_EXPIRES_IN',
  REFRESH_TOKEN_SECRET: 'REFRESH_TOKEN_SECRET',
  REFRESH_TOKEN_EXPIRES_IN: 'REFRESH_TOKEN_EXPIRES_IN',
};
