export const FYNO_ENV_CONST = {
  FYNO_START_BASE_URL: 'FYNO_START_BASE_URL',
  FYNO_END_BASE_URL: 'FYNO_END_BASE_URL',
  FYNO_VERSION_1: 'FYNO_VERSION_1',
  FYNO_CALLBACK_URL_NAME: 'FYNO_CALLBACK_URL_NAME',
};
