export const DATABASE_NAME_CONST = {
  FULFILLMENT_DB: 'FULFILLMENT',
  DISTRIBUTOR_DB: 'DISTRIBUTOR',
};

export const COLLECTION_NAME_CONST = {
  DELIVERY_AGENT: 'DeliveryAgent',
  MP_USER: 'MPUser',
  STATUS_TRACKING: 'StatusTracking',
  STATUS_TRACKING_LOGS: 'StatusTrackingLogs',
};

export const REPOSITORY_MODEL_PROVIDER_CONST = {
  DELIVERY_AGENT_MODEL: 'DELIVERY_AGENT_MODEL',
  MP_USER_MODEL: 'MP_USER_MODEL',
  STATUS_TRACKING_MODEL: 'STATUS_TRACKING_MODEL',
  STATUS_TRACKING_LOGS_MODEL: 'STATUS_TRACKING_LOGS_MODEL',
};

export const REPOSITORY_MODEL_CONST = {
  DELIVERY_AGENT_MODEL: 'DeliveryAgentModel',
  MP_USER_MODEL: 'MPUserModel',
  STATUS_TRACKING_MODEL: 'StatusTrackingModel',
  STATUS_TRACKING_LOGS_MODEL: 'StatusTrackingLogsModel',
};
