export const DATABASE_NAME_CONST = {
  FULFILLMENT: 'FULFILLMENT',
};

export const COLLECTION_NAME_CONST = {
  NOTIFICATION: 'Notification',
  NOTIFICATION_LOG: 'NotificationLog',
  NOTIFICATION_SECRETS: 'NotificationSecrets',
  DELIVERY_AGENT: 'DeliveryAgent',
  MP_USER: 'MPUser',
};

export const REPOSITORY_MODEL_PROVIDER_CONST = {
  NOTIFICATION_MODEL: 'NOTIFICATION_MODEL',
  NOTIFICATION_LOG_MODEL: 'NOTIFICATION_LOG_MODEL',
  NOTIFICATION_SECRETS_MODEL: 'NOTIFICATION_SECRETS_MODEL',
  DELIVERY_AGENT_MODEL: 'DELIVERY_AGENT_MODEL',
  MP_USER_MODEL: 'MP_USER_MODEL',
};

export const REPOSITORY_MODEL_CONST = {
  NOTIFICATION_MODEL: 'NotificationModel',
  NOTIFICATION_LOG_MODEL: 'NotificationLogModel',
  NOTIFICATION_SECRETS_MODEL: 'NotificationSecretsModel',
  DELIVERY_AGENT_MODEL: 'DeliveryAgentModel',
  MP_USER_MODEL: 'MPUserModel',
};
