export enum OTEL_ENV_CONST {
  EVN_TYPE = 'ENV_TYPE',
  OTEL_BASE_URL = 'OTEL_BASE_URL',
  OTEL_TRACE_EXPORTER_END_POINT = 'OTEL_TRACE_EXPORTER_END_POINT',
  OTEL_METRIC_EXPORTER_END_POINT = 'OTEL_METRIC_EXPORTER_END_POINT',
  OTEL_TRACE_EXPORTER_PORT = 'OTEL_TRACE_EXPORTER_PORT',
  OTEL_METRIC_EXPORTER_PORT = 'OTEL_METRIC_EXPORTER_PORT',
  OTEL_LOG_EXPORTER_PORT = 'OTEL_LOG_EXPORTER_PORT',
}

export enum OTEL_PORT_CONST {
  OTEL_TRACE_EXPORTER_PORT = '4318',
  OTEL_METRIC_EXPORTER_PORT = '4318',
  OTEL_LOG_EXPORTER_PORT = '3100',
}

export enum OTEL_CONFIG_CONST {
  EXPORT_INTERVAL_MILLIS = 30000,
}

export enum LOG_CONFIG_CONST {
  INTERVAL = 30,
  TIMEOUT = 30000,
}

export enum LOG_EXPORTER_CONST {
  CONSOLE = 'CONSOLE',
  LOKI = 'LOKI',
  BOTH = 'BOTH',
}

export enum LOG_LEVELS_CONST {
  ERROR = 'error',
  WARN = 'warn',
  INFO = 'info',
  VERBOSE = 'verbose',
  DEBUG = 'debug',
  test = 'test',
}

export enum ENV_TYPE_CONST {
  DEV = 'dev',
  QA = 'qa',
  PROD = 'prod',
}
