export enum STATUS_TRACKING_STATUS_ENUM {
  MANIFESTED = "MANIFESTED",
  CANCELED = "CANCELED",
}

export enum ORDER_STATUS_ENUM {
  NEW = "NEW",
  RECEIVED = "RECEIVED",
  READY_FOR_DISPATCH = "READY_FOR_DISPATCH",
  CANCELED = "CANCELED",
}

export enum SHIPPING_TYPE_ENUM {
  EXPRESS = "EXPRESS",
}

// export enum DELIVERY_MODE_ENUM {
//   DOOR_TO_DOOR = "DOOR_TO_DOOR",
//   DOOR_TO_VENDOR = "DOOR_TO_VENDOR"
// }

export enum SERVICE_TYPE_ENUM {
  STANDARD = "STANDARD",
}

export enum TRAVEL_TYPE_ENUM {
  SURFACE = "SURFACE",
  AIR = "AIR",
}

export enum PARTNER_CODE_ENUM {
  SMILE = "SMILE",
  BIGSHIP = "BIGSHIP",
  TSAW = "TSAW",
  SHIPYAARI = "SHIPYAARI",
  DEFAULT = "DEFAULT",
}

export enum ENDPOINT_ID_ENUM {
  AUTH_TOKEN = "AUTH_TOKEN",
  CREATE_MANIFEST = "CREATE_MANIFEST",
  CREATE_ORDER = "CREATE_ORDER",
  GET_ORDER_DETAILS = "GET_ORDER_DETAILS",
  CANCEL_ORDER = "CANCEL_ORDER",
  PUSH_ORDER_TO_DRS = "PUSH_ORDER_TO_DRS",
  PUSH_ORDERS_TO_PRS = "PUSH_ORDERS_TO_PRS",
  PUSH_ORDER_TO_TRACKING = "PUSH_ORDER_TO_TRACKING",
  MANIFEST_ORDER_TO_TRACKING = "MANIFEST_ORDER_TO_TRACKING",
}

export enum ORDER_TYPE_ENUM {
  ECOMM = "ECOMM",
  CARGO = "CARGO",
  COURIER = "COURIER",
}
