export enum STATUS_TRACKING_STATUS_ENUM {
  MANIFESTED = "MANIFESTED",
  CANCELED = "CANCELED",
}

export enum ORDER_STATUS_ENUM {
  NEW = "NEW",
  RECEIVED = "RECEIVED",
  READY_FOR_DISPATCH = "READY_FOR_DISPATCH",
  CANCELED = "CANCELED",
}

export enum SHIPPING_TYPE_ENUM {
  EXPRESS = "EXPRESS",
}

// export enum DELIVERY_MODE_ENUM {
//   DOOR_TO_DOOR = "DOOR_TO_DOOR",
//   DOOR_TO_VENDOR = "DOOR_TO_VENDOR"
// }

export enum SERVICE_TYPE_ENUM {
  STANDARD = "STANDARD",
}

export enum TRAVEL_TYPE_ENUM {
  SURFACE = "SURFACE",
  AIR = "AIR",
}

export enum PARTNER_CODE_ENUM {
  SMILE = "SMILE",
  BIGSHIP = "BIGSHIP",
  TSAW = "TSAW",
  SHIPYAARI = "SHIPYAARI",
  DEFAULT = "DEFAULT",
  DHL = "DHL",
  SMILE_HYPERLOCAL = "SMILE_HYPERLOCAL",
  INDIA_POST_INTERNATIONAL = "INDIA_POST_INTERNATIONAL",
  INDIA_POST_DOMESTIC = "INDIA_POST_DOMESTIC",
  UNIUNI = "UNIUNI",
  PORTER = "porter_2w",
  DELHIVERY = "DELHIVERY",
  SMILE_HUBOPS = "smile_hubops",
  ARAMEX = "ARAMEX",
  FEDEX = "FEDEX",
  BARAL = "sunil_baral",
  URBANBOLT = "urbanbolt",
  SHIPCUBE = "SHIPCUBE",
  XPRESSBEES_B2C = "ebb2c",
  XPRESSBEES_B2B = "dharmendra",
  DPWORLD = "DPWORLD",
  NAQEL = "NAQEL"
}

export enum ENDPOINT_ID_ENUM {
  AUTH_TOKEN = "AUTH_TOKEN",
  CREATE_MANIFEST = "CREATE_MANIFEST",
  CREATE_ORDER = "CREATE_ORDER",
  GET_ORDER_DETAILS = "GET_ORDER_DETAILS",
  CANCEL_ORDER = "CANCEL_ORDER",
  UPDATE_ORDER = "UPDATE_ORDER",
  CREATE_PICKUP = "CREATE_PICKUP",
  CANCEL_PICKUP = "CANCEL_PICKUP",
  PUSH_ORDER_TO_DRS = "PUSH_ORDER_TO_DRS",
  PUSH_ORDERS_TO_PRS = "PUSH_ORDERS_TO_PRS",
  PUSH_ORDER_TO_TRACKING = "PUSH_ORDER_TO_TRACKING",
  MANIFEST_ORDER_TO_TRACKING = "MANIFEST_ORDER_TO_TRACKING",
  SELLER_ECOMM_WEBHOOK = "SELLER_ECOMM_WEBHOOK",
  PUSH_ORDER_TO_HUBOPS = "PUSH_ORDER_TO_HUBOPS",
  UPDATE_ORDER_TO_HUBOPS = "UPDATE_ORDER_TO_HUBOPS",
  UPDATE_PARTNER_TO_HUBOPS = "UPDATE_PARTNER_TO_HUBOPS",
}

export enum ORDER_TYPE_ENUM {
  ECOMM = "ECOMM",
  CARGO = "CARGO",
  COURIER = "COURIER",
  INTERNATIONAL = "international",
}
